import {CoreQueryOptions} from "@app-global";

export class OrgLicenseQueryOptions extends CoreQueryOptions{}

export class LicenseSetting {
    id: string;
    apiBanCount: number;
    apiKeyGenerationAllowed: boolean;
    licenseValidityWarningDay: number;
    licenseGraceDay: number;

    constructor(model: any = <any>{}){
        const { id, apiBanCount, apiKeyGenerationAllowed, licenseValidityWarningDay, licenseGraceDay } = model;
        this.id = id;
        this.apiBanCount = apiBanCount;
        this.apiKeyGenerationAllowed = apiKeyGenerationAllowed;
        this.licenseValidityWarningDay = licenseValidityWarningDay;
        this.licenseGraceDay = licenseGraceDay;
    }
}

export class SoftwareLicenseFeature {
    id: number;
    licenseTypeId: number;
    licenseType: string;
    value: string;
    constructor(model: any = <any>{}){
        const { id, value, licenseTypeId, licenseType } = model;
        this.id = id;
        this.value = value;
        this.licenseTypeId = licenseTypeId;
        this.licenseType = licenseType;
    }
}

export class LicensingFeature {
    id: string;
    name: string;
    description: string;
    sortOrder: number;
    softwareLicenseFeatures: Array<SoftwareLicenseFeature>;

    constructor(model: any = <any>{}){
        const { id, name, description, sortOrder, softwareLicenseFeatures } = model;
        this.id = id;
        this.name = name;
        this.description = description;
        this.sortOrder = sortOrder;
        const temp = (softwareLicenseFeatures || []).reduce(
            (prev, next) => {
                prev[`${id}${next.licenseTypeId}`] = next;
                return prev
            },
            {}
        );
        this.softwareLicenseFeatures = temp;
        //this.softwareLicenseFeatures = (softwareLicenseFeatures || []).map(r => new SoftwareLicenseFeature(r));
    }
}

export class ApiKeys {
    id: string;
    key: string;
    requestIP: string;
    isAutoGenerated: boolean;

    constructor(model: any = <any>{}){
        const { id, key, requestIP, isAutoGenerated } = model;
        this.id = id;
        this.key = key;
        this.requestIP = requestIP;
        this.isAutoGenerated = isAutoGenerated;
    }
}

export class Software {
    id: string;
    name: string;
    description: string;
    apiKeys: Array<ApiKeys>;
    licenseSetting: LicenseSetting;
    licensingFeatures: Array<LicensingFeature>;

    constructor(model: any = <any>{}){
        const { id, name, description, apiKeys, licenseSetting, licensingFeatures } = model;
        this.id = id;
        this.name = name;
        this.description = description;
        this.licenseSetting = new LicenseSetting(licenseSetting);
        this.licensingFeatures = (licensingFeatures || []).map(r => new LicensingFeature(r));
        this.apiKeys = (apiKeys || []).map(r => new ApiKeys(r));
    }
}

export class LicenseType {
    id: number;
    name: string;

    sortOrder: number;
    isRecommended: boolean;

    softwareId: number;
    validityIndays: number;

    rate: number;
    discount: number;
    constructor(model: any = <any>{}){
        const {
            id, name, sortOrder, isRecommended, softwareId, validityIndays,
            rate, discount
        } = model;
        this.id = id;
        this.name = name;
        this.sortOrder = sortOrder;
        this.isRecommended = isRecommended;

        this.softwareId = softwareId;
        this.validityIndays = validityIndays;

        this.rate = rate;
        this.discount = discount;
    }
}

export class OrgLicense {
  id: string;
  licenseNo: string;
  licenseType: string;
  isDefault: boolean;
  isExpired: boolean;
  remark: string;
  status: string;
  software: Software;
  licenseTypes: Array<LicenseType>;

  constructor(model: any = <any>{}){
    const { id, licenseNo, remark, status, licenseType, isDefault, isExpired, software, licenseTypes } = model;
    this.id = id;
    this.licenseNo = licenseNo;
    this.licenseType = licenseType;
    this.isDefault = isDefault;
    this.isExpired = isExpired;
    this.remark = remark;
    this.status = status;
    this.software = new Software(software);
    this.licenseTypes = (licenseTypes || []).map(r => new LicenseType(r));
  }
}

export class OrgLicenseSerializer {
  fromJson(json: any): OrgLicense {
    return new OrgLicense(json);
  }

  toJson(data: any): any {
    return {
      id: data.id,
      name: data.name,
      parentId: data.parentId,
      description: data.description
    };
  }
}
